In [2]:
import numpy as np
a4 = np.arange(1, 4, 1)


In [3]:
a4

array([1, 2, 3])

In [7]:
a4.ndim == 1

True

In [8]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4


In [9]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [11]:
a1 = np.random.rand(4)
a1


array([0.60787067, 0.2298354 , 0.69321736, 0.99382514])

In [15]:
a5 = np.linspace(1 ,4, 4)
a5

array([1., 2., 3., 4.])

In [28]:
import re

def names():
    simple_string = """Amy is 5 years old, and her sister Mary is 2 years old. 
    Ruth and Peter, their parents, have 3 kids."""

    # Define a regular expression to match names
    name_pattern = r'\b[A-Z][a-z]*\b'

    # Use findall to extract all matches
    name_list = re.findall(name_pattern, simple_string)

    return name_list

result = names()
print(result)


['Amy', 'Mary', 'Ruth', 'Peter']


In [29]:
assert len(names()) == 4, "There are four names in the simple_string"

In [9]:
import numpy as np

a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [12]:
b = a[4:6]
b[:] = 40
a

array([ 0,  1,  2,  3, 40, 40,  6,  7])

In [11]:
c = a[4] + a[6]
c

46

In [14]:
import re
s = 'ABCAC'

In [18]:
bool(re.match('A', s)) == True

True

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nhl_df = pd.read_csv("assets/nhl.csv")
cities = pd.read_html("assets/wikipedia_data.html")[1]
# Exclude the last row of "Totals", and select the columns we need.
cities = cities.iloc[:-1, [0, 3, 5, 6, 7, 8]] 

def clean_nhl_df(df=nhl_df):
    # Remove "*" from the team names
    nhl_df['team'] = nhl_df['team'].str.rstrip('*')
    
    # Remove rows corresponding to divisions
    nhl_df_cleaned = nhl_df[~nhl_df['team'].str.contains('Division')]
    
    # Filter NHL data for the year 2018
    return nhl_df_cleaned[nhl_df_cleaned["year"] == 2018]

def clean_cities_column(team):
    # Remove notes and extra spaces
    return re.sub(r'\[.*\]|—\s*', '', team)

# Create a mapping between NHL team names and metropolitan areas
team_mapping_nhl = {
        'Tampa Bay Lightning': 'Tampa Bay Area',
        'Boston Bruins': 'Boston',
        'Toronto Maple Leafs': 'Toronto',
        'Florida Panthers': 'Miami–Fort Lauderdale',
        'Detroit Red Wings': 'Detroit',
        'Montreal Canadiens': 'Montreal',
        'Ottawa Senators': 'Ottawa',
        'Buffalo Sabres': 'Buffalo',
        'Washington Capitals': 'Washington, D.C.',
        'Pittsburgh Penguins': 'Pittsburgh',
        'Philadelphia Flyers': 'Philadelphia',
        'Columbus Blue Jackets': 'Columbus',
        'New Jersey Devils': 'New York City',
        'Carolina Hurricanes': 'Raleigh',
        'New York Islanders': 'New York City',
        'New York Rangers': 'New York City',
        'Nashville Predators': 'Nashville',
        'Winnipeg Jets': 'Winnipeg',
        'Minnesota Wild': 'Minneapolis–Saint Paul',
        'Colorado Avalanche': 'Denver',
        'St. Louis Blues': 'St. Louis',
        'Dallas Stars': 'Dallas–Fort Worth',
        'Chicago Blackhawks': 'Chicago',
        'Vegas Golden Knights': 'Las Vegas',
        'Anaheim Ducks': 'Los Angeles',
        'San Jose Sharks': 'San Francisco Bay Area',
        'Los Angeles Kings': 'Los Angeles',
        'Calgary Flames': 'Calgary',
        'Edmonton Oilers': 'Edmonton',
        'Vancouver Canucks': 'Vancouver',
        'Arizona Coyotes': 'Phoenix',
}

def nhl_correlation():
    nhl_2018 = clean_nhl_df()
    
    # Clean the Big 4 columns in cities  
    cities["NHL"] = cities["NHL"].apply(clean_cities_column).replace('', np.NaN)

    # Create a new column for metropolitan area in the NHL dataset
    nhl_2018["Metropolitan area"] = nhl_2018["team"].map(team_mapping_nhl)

    # Merge NHL data with cities data
    merged_df = pd.merge(nhl_2018, cities, how="left", on="Metropolitan area")
    
    # Rename the Population column
    merged_df = merged_df.rename(columns={"Population (2016 est.)[8]": "Population"})
    
    # Convert columns to appropriate data types
    merged_df[['W', 'L', 'Population']] = merged_df[['W', 'L', 'Population']].astype(float)
    merged_df["WinLossRatio"] = merged_df["W"] / (merged_df["W"] + merged_df["L"])
    
    # Group by metropolitan area and calculate average win/loss ratio
    win_loss_df = merged_df.groupby("Metropolitan area").agg({'Population': 'mean', 'WinLossRatio': 'mean'})
    
    population_by_region = win_loss_df["Population"]
    win_loss_by_region   = win_loss_df["WinLossRatio"]

    assert len(population_by_region) == len(win_loss_by_region), "Q1: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q1: There should be 28 teams being analysed for NHL"

    corr = stats.pearsonr(population_by_region, win_loss_by_region)[0]
    return corr

# Call the function
correlation_result = nhl_correlation()
print(correlation_result)


FileNotFoundError: [Errno 2] No such file or directory: 'assets/nhl.csv'

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

nba_df=pd.read_csv("assets/nba.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def clean_nba_df(df=nba_df):
    # Remove "*" and other characters from the team names
    nba_df['team'] = nba_df['team'].str.replace(r'\*?\s*\((\d+)\)?$', '').str.strip()

    # Filter NBA data for the year 2018
    return nba_df[nba_df["year"] == 2018]

# Create a mapping between NBA team names and metropolitan areas
team_mapping_nba = {
        'Toronto Raptors': 'Toronto',
        'Boston Celtics': 'Boston',
        'Philadelphia 76ers': 'Philadelphia',
        'Cleveland Cavaliers': 'Cleveland',
        'Indiana Pacers': 'Indianapolis',
        'Miami Heat': 'Miami–Fort Lauderdale',
        'Milwaukee Bucks': 'Milwaukee',
        'Washington Wizards': 'Washington, D.C.',
        'Detroit Pistons': 'Detroit',
        'Charlotte Hornets': 'Charlotte',
        'New York Knicks': 'New York City',
        'Brooklyn Nets': 'New York City',
        'Chicago Bulls': 'Chicago',
        'Orlando Magic': 'Orlando',
        'Atlanta Hawks': 'Atlanta',
        'Houston Rockets': 'Houston',
        'Golden State Warriors': 'San Francisco Bay Area',
        'Portland Trail Blazers': 'Portland',
        'Oklahoma City Thunder': 'Oklahoma City',
        'Utah Jazz': 'Salt Lake City',
        'New Orleans Pelicans': 'New Orleans',
        'San Antonio Spurs': 'San Antonio',
        'Minnesota Timberwolves': 'Minneapolis–Saint Paul',
        'Denver Nuggets': 'Denver',
        'Los Angeles Clippers': 'Los Angeles',
        'Los Angeles Lakers': 'Los Angeles',
        'Sacramento Kings': 'Sacramento',
        'Dallas Mavericks': 'Dallas–Fort Worth',
        'Memphis Grizzlies': 'Memphis',
        'Phoenix Suns': 'Phoenix'
}

def nba_correlation():
    nba_2018 = clean_nba_df()

    # Clean the Big 4 columns in cities
    cities["NBA"] = cities["NBA"].apply(clean_cities_column).replace('', np.NaN)
    
    # Create a new column for metropolitan area in the NBA dataset
    nba_2018["Metropolitan area"] = nba_2018["team"].map(team_mapping_nba)

    # Merge NBA data with cities data
    merged_df = pd.merge(nba_2018, cities, how="left", on="Metropolitan area")

    # Rename the Population column
    merged_df = merged_df.rename(columns={"Population (2016 est.)[8]": "Population"})
    
    # Convert columns to appropriate data types
    merged_df[['W', 'L', 'Population']] = merged_df[['W', 'L', 'Population']].astype(float)
    merged_df["WinLossRatio"] = merged_df["W"] / (merged_df["W"] + merged_df["L"])
    
    # Group by metropolitan area and calculate average win/loss ratio
    win_loss_df = merged_df.groupby("Metropolitan area").agg({'WinLossRatio': 'mean', 'Population': 'mean'})
    
    population_by_region = win_loss_df["Population"] # pass in metropolitan area population from cities
    win_loss_by_region = win_loss_df["WinLossRatio"] # pass in win/loss ratio from nba_df in the same order as cities["Metropolitan area"]

    assert len(population_by_region) == len(win_loss_by_region), "Q2: Your lists must be the same length"
    assert len(population_by_region) == 28, "Q2: There should be 28 teams being analysed for NBA"

    corr = stats.pearsonr(population_by_region, win_loss_by_region)[0]
    return corr

# Call the function
correlation_result_nba = nba_correlation()
print(correlation_result_nba)

In [ ]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import re

mlb_df=pd.read_csv("assets/mlb.csv")
nhl_df=pd.read_csv("assets/nhl.csv")
nba_df=pd.read_csv("assets/nba.csv")
nfl_df=pd.read_csv("assets/nfl.csv")
cities=pd.read_html("assets/wikipedia_data.html")[1]
cities=cities.iloc[:-1,[0,3,5,6,7,8]]

def clean_and_merge_df(league_name, league_df, cities_df):
    # Clean the Big 4 columns in cities
    cities_df[league_name] = cities_df[league_name].apply(clean_cities_column).replace('', np.NaN)

    # Create a new column for metropolitan area in the dataset
    if league_name == 'NHL':
        league_df = clean_nhl_df(league_df)
        league_df["Metropolitan area"] = league_df["team"].map(team_mapping_nhl)
    elif league_name == 'NBA':
        league_df = clean_nba_df(league_df)
        league_df["Metropolitan area"] = league_df["team"].map(team_mapping_nba)
    elif league_name == 'MLB':
        league_df["Metropolitan area"] = league_df["team"].map(team_mapping_mlb)
    elif league_name == 'NFL':
        league_df = clean_nfl_df(league_df)
        league_df["Metropolitan area"] = league_df["team"].map(team_mapping_nfl)
    else:
        print("Invalid League Name!")

    # Merge data with cities data
    merged_df = pd.merge(league_df, cities_df, how="left", on="Metropolitan area")

    # Rename the Population column
    merged_df = merged_df.rename(columns={"Population (2016 est.)[8]": "Population"})
    
    # Convert columns to appropriate data types
    merged_df[['W', 'L', 'Population']] = merged_df[['W', 'L', 'Population']].astype(float)

    # Group by metropolitan area and calculate average win/loss ratio
    win_loss_df = merged_df.groupby("Metropolitan area").agg({'W': 'mean', 'L': 'mean', 'Population': 'mean'})
    win_loss_df["WinLossRatio"] = win_loss_df["W"] / (win_loss_df["W"] + win_loss_df["L"])

    return win_loss_df


def sports_team_performance():
    
    NHL_2018 = clean_and_merge_df('NHL', nhl_df, cities)
    NBA_2018 = clean_and_merge_df('NBA', nba_df, cities)
    MLB_2018 = clean_and_merge_df('MLB', mlb_df, cities)
    NFL_2018 = clean_and_merge_df('NFL', nfl_df, cities)
    
    # Note: p_values is a full dataframe, so df.loc["NFL","NBA"] should be the same as df.loc["NBA","NFL"] and
    # df.loc["NFL","NFL"] should return np.nan
    sports = ['NHL', 'NBA', 'MLB', 'NFL']
    p_values = pd.DataFrame({k:np.nan for k in sports}, index=sports)
    
    for sport1 in sports:
        for sport2 in sports:
            if sport1 != sport2:
                common_cities = set(eval(f'{sport1}_2018.index')) & set(eval(f'{sport2}_2018.index'))
                array1 = eval(f'{sport1}_2018.loc[{sport1}_2018.index.isin(common_cities), "WinLossRatio"]')
                array2 = eval(f'{sport2}_2018.loc[{sport2}_2018.index.isin(common_cities), "WinLossRatio"]')
                _, p_value = stats.ttest_rel(array1, array2)
                p_values.loc[sport1, sport2] = p_value
    
    assert abs(p_values.loc["NBA", "NHL"] - 0.02) <= 1e-2, "The NBA-NHL p-value should be around 0.02"
    #assert abs(p_values.loc["MLB", "NFL"] - 0.80) <= 1e-2, "The MLB-NFL p-value should be around 0.80"
    return p_values

# Call the function
p_values_result = sports_team_performance()
print(p_values_result)